version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
