// Generated by CoffeeScript 1.12.7
(function() {
  var _rectangle, _string, process, rectangle, string;

  process = require("process");


  /*
  a = 10
  func = -> b = 20; process.write stdout, 'local var ' + b
  do func
  f = (a, b, c) -> process.write stdout, a, b, c
  f 12, 32, 42
  process.write stdout, 'global var ' + a + '\n' + b
  str_inter = """
    one #{do func}
       two
          three
  """
  str_inter_not = '''
          one
      two
    three #{do func}
  '''
   */

  string = (function() {
    function string() {}

    return string;

  })();

  _string = new string;

  rectangle = (function() {
    function rectangle(w, h) {
      this.width = w;
      this.height = h;
    }

    rectangle.prototype.get_area = function() {
      return this.width * this.height;
    };

    rectangle.prototype.fn_to_test = function() {
      return (function(_this) {
        return function() {
          return _this.width;
        };
      })(this)();
    };

    return rectangle;

  })();

  _rectangle = new rectangle(10, 20);

  console.log(_rectangle.get_area());

  console.log(_rectangle.fn_to_test());

}).call(this);
