// Generated by CoffeeScript 1.12.7
(function() {
  var a, b, bool, double, heredoc_string, is_ready, number, on_line, string;

  console.log('hello, coffee');


  /*
   long comment
   */

  a = 10;

  b = 20;

  bool = true;

  number = 2912;

  double = 42.23;

  bool = true;

  bool = false;

  bool = true;

  bool = false;

  on_line = false;

  is_ready = true;

  string = 'some string';

  string = 'some very long string';

  heredoc_string = "\nlorem ipsum dolor sit amet,\nconsectetur adipsicinp elit,\nmagnam, debitis, veritatis,\nvero, maxine numquem ipsan nostrum";

}).call(this);
