version: '3'
services:
  websocket:
    build: './websocket'
    ports: 
      - '3001:8000'
      - "3000"
      - "3000-3005"
      - "8000:8000"
      - "9090-9091:8080-8081"
      - "49100:22"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:5000-5010:5000-5010"
      - "6060:6060/udp"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/chat
  authserver:
    build: './authserver'
    ports:
      - '3002:3000'
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/chat
  db:
    image: mongo
    ports:
      - '27017:27017'
