name: CI\/CD basic examples
env:
  APPLICATION_NAME: "node"
  DEPLOY_PACKAGE_NAME: "node-to-test version ${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script(print hello world)
        run: echo Hello, world!
      
      - name: Execute some commands
        run: |
          echo Hello, message one
          echo Hello, message two...
          echo Application name ${{ env.APPLICATION_NAME }}
          echo Deploy package name ${{ env.DEPLOY_PACKAGE_NAME }}
          
      - name: List current folder before cloning
        run: ls -la   
        
      - name: Clone git repository
        uses: actions/checkout@v1  
      
      - name: List current folder after cloning
        run: ls -la   
  
  my-deploy:
    runs-on: ubuntu-latest
    env:
      VARIABLE_1: "This is a test varible for my-deploy job"
      VARIABLE_2: ""
    needs:
      - my-testing
    
    steps:
      - name: deploy testing
        run: echo Hello, world from deploy
      
      - name: Check for aws package
        run: aws --version
        
      - name: Check for zip cli
        run: zip --version
      
      - name: Execute
        env:
          LOCAL_VARIABLE: "This is local variable for step execute"
        run: |
          echo LOCAL ENV variables 1 = $LOCAL_VARIABLE
          echo Deploy package name ${{ env.DEPLOY_PACKAGE_NAME }}
          echo ENV variables var 1 = ${{ env.VARIABLE_1 }}
          echo ENV variables var 2 = ${{ env.VARIABLE_2 }}
