name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy package to aws
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DO }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY_DO }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH_DO }} && git pull origin master
          docker rm -f ${{ secrets.CONTAINER }}
          docker build -f Dockerfile --tag ${{ secrets.REGISTERY }}/${{ secrets.CONTAINER }}:latest .
          docker run -d --name ${{ secrets.CONTAINER }} -p 3000:3000 ${{ secrets.REGISTERY }}/${{ secrets.CONTAINER }}:latest
