version: "3.7"

services:
  db:
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  my-postgres-data:
