name: CI\/CD basic examples
env:
  APPLICATION_NAME: "node"
  DEPLOY_PACKAGE_NAME: "node-to-test version ${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script(print hello world)
        run: echo Hello, world!
      
      - name: Execute some commands
        run: |
          echo Hello, message one
          echo Hello, message two...
          echo Application name ${{ env.APPLICATION_NAME }}
          echo Deploy package name ${{ env.DEPLOY_PACKAGE_NAME }}
          
      - name: List current folder
        run: ls -la   
  
  my-deploy:
    runs-on: ubuntu-latest
    needs:
      - my-testing
    
    steps:
      - name: deploy testing
        run: echo Hello, world from deploy
      
      - name: Execute
        run: |
          echo Deploy package name ${{ env.DEPLOY_PACKAGE_NAME }}
